###########
# ENV VARS:
# - DOCKER_USERNAME
# - DOCKER_PASSWORD
# - GITHUB_TOKEN (default)
###########

name: Publish Docker Image

on:
  push:
    paths:
      - 'release-versions/*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Get current repository
        uses: actions/checkout@v1

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(cat release-versions/strapi-latest.txt)

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build (default => debian)
        uses: docker/build-push-action@v2
        with:
          context: ./images/strapi-debian
          build-args: |
            STRAPI_VERSION=${{steps.vars.outputs.tag}}
            NODE_VERSION=18
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}:${{ steps.vars.outputs.tag }}
            ${{ steps.meta.outputs.tags }}:latest
            
      - name: Build (alpine)
        uses: docker/build-push-action@v2
        with:
          context: ./images/strapi-alpine
          build-args: |
            STRAPI_VERSION=${{ steps.vars.outputs.tag }}
            NODE_VERSION=18
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}:${{ steps.vars.outputs.tag }}-alpine
            ${{ steps.meta.outputs.tags }}:latest-alpine

      - name: Build (alpine-prod)
        uses: docker/build-push-action@v2
        with:
          context: ./images/strapi-alpine
          build-args: |
            STRAPI_VERSION=${{ steps.vars.outputs.tag }}
            NODE_VERSION=18
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}:${{ steps.vars.outputs.tag }}-alpine-prod
            ${{ steps.meta.outputs.tags }}:latest-alpine-prod

      - name: Docker Hub Description (README.md)
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: TomTaylorCo/docker-strapi
          readme-filepath: README.md

      - name: Create Release in GitHub
        id: create_release
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{steps.vars.outputs.tag}}
          release_name: Release ${{steps.vars.outputs.tag}}
          body: strapi v${{steps.vars.outputs.tag}}
